### PR TITLE
Give better non-null error

### PR DESCRIPTION
**Pull request by dszopa**
- Include the class name with class path to show what object the field relates to

### CODE REVIEW

**Comment by dszopa** [comment]
It appears that Travis is running against kotlin 1.0.87, a more recent version is required for the javaType function on KTypes

**Comment by sargunv** [comment]
Thanks for the PR! It's actually an old version of Kobalt. I'm preparing a commit to fix that now.

**Comment by dszopa** [comment]
Not sure why `javaType` didn't work, but `javaClass` seems to work fine as a replacement

**Comment by sargunv** [comment]
Released version 0.2.0 with this

**Pull request merged**
